remote_theme: minimal-mistakes@master

plugins:
- jekyll-remote-theme

title: Nut Recognizer
description: Unlock the Secrets of Nature's Bounty - An Image Classification API with Advanced Recognition for 14 Delicious Edible Nuts!

author:
  name: Nasrin Akter Ripa