# -*- coding: utf-8 -*-
"""interface.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tDOEZZAV8dQARnd0b9S-nkd27rPaob3E
"""

!pip install -Uqq fastai gradio nbdev

"""## Nut Recognizer"""

from fastai.vision.all import *

#!export
from fastai.vision.all import load_learner
import gradio as gr

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/My Drive/MasterCourse/Nut Recognizer

#!export
model = load_learner('models/nut-recognizer-v4.pkl')

#!export
nut_labels = (
    "raw Almonds",
    "raw Walnuts",
    "raw Cashew nut",
    "raw Pecans",
    "raw Peanut",
    "raw Pili nut",
    "raw Pistachios nut",
    "raw Hazelnuts",
    "raw Brazil nut",
    "raw Maccademia nut",
    "raw Pine nut",
    "raw Chestnut",
    "raw Hickory nut",
    "raw Ginkgo nut"
)

def recognize_image(image):
  pred, idx, probs = model.predict(image)
  return dict(zip(nut_labels, map(float, probs)))

img = PILImage.create(f'cashew.jpg')
img.thumbnail((192,192))
img

recognize_image(img)

image = gr.inputs.Image(shape=(192,192))
label = gr.outputs.Label(num_top_classes=5)
examples = [
    'almond1.jpg',
    'peanuts.jpg',
    'cashew.jpg'
    ]

iface = gr.Interface(fn=recognize_image, inputs=image, outputs=label, examples=examples)
iface.launch(inline=False, share = True)

# https://huggingface.co/spaces/nasrin2023ripa/nut-recognizer